Pandas

In [ ]:
import pandas as pd

#Series=>A pandas series is one-dimensional labeled data structure

numbers=[10,20,30,40,50]
series=pd.Series(numbers)
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#Acessing series values
print(series[0])
print(series[1])

10
20

In [ ]:
#creating a series with custom index
marks=[85,90,78]
student_marks=pd.Series(
    marks,
    index=["Ananya","Swarna","Harini"]
)
student_marks

Ananya    85
Swarna    90
Harini    78
dtype: int64

In [4]:
student_marks["Swarna"]

np.int64(90)

In [ ]:
#series from a dictionary
#keys become indexes and values become series values
student={
    "name":"Swarna",
    "age":22,
    "role":"AI-Ml Engineer"
}
data=pd.Series(student)
data

name            Swarna
age                 22
role    AI-Ml Engineer
dtype: object

In [ ]:
#DatFrame=> A pandas dataframe is a two-dimensional tabular data structure consisting of rows and columns
#Creating dataFrames
data={
    "Name":["Ananya","Swarna","Harini"],
    "Age":[22,21,22],
    "Course":["Java","Data Science","Full Stack"]
}
df=pd.DataFrame(data)
df

     Name  Age        Course
0  Ananya   22          Java
1  Swarna   21  Data Science
2  Harini   22    Full Stack

In [7]:
#creating a df using a list of lists
data=[
    ["Ananya",22,"Java"],
    ["Swarna",21,"Data Science"],
    ["Harini",22,"Full Stack"]
]
df=pd.DataFrame(
    data,
    columns=["Name","Age","Course"]
)
df

     Name  Age        Course
0  Ananya   22          Java
1  Swarna   21  Data Science
2  Harini   22    Full Stack

In [8]:
#creating a df from a list of dictionaries
data=[
    {
        "Name":"Ananya",
        "Age":22,
        "Course":"Java"
    },
    {
        "Name":"Swarna",
        "Age":21,
        "Course":"Data Science"

    },
    {
        "Name":"Harini",
        "Age":22,
        "Course":"Full Stack"
    }
]
df=pd.DataFrame(data)
df

     Name  Age        Course
0  Ananya   22          Java
1  Swarna   21  Data Science
2  Harini   22    Full Stack

In [ ]:
#creating an empty dataframe
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
#Reading data using read_csv()
#pd.read_csv("filename.csv")=>reads the CSV filr and converts it into a pandas dataframe
df=pd.read_csv("employees.csv")
df

     Name  Age Department
0  Swarna   22         IT
1   Rahul   24         HR
2   Priya   23    Finance
3   Arjun   25         IT
4   Sneha   21  Marketing
5   Kiran   26         IT
6  Anjali   22         HR

In [12]:
#Exploring datasets
#Pandas provides several useful methods
#head()
#tail()
#info()
#describe()

#head()=> method displays the first few rows of a dataframe i.e by default the first 5 rows
df.head()

     Name  Age Department
0  Swarna   22         IT
1   Rahul   24         HR
2   Priya   23    Finance
3   Arjun   25         IT
4   Sneha   21  Marketing

In [14]:
df.head(3)

     Name  Age Department
0  Swarna   22         IT
1   Rahul   24         HR
2   Priya   23    Finance

In [16]:
#tail()=>displays the last few rows of a dataframe i.e by default the last 5 rows
df.tail()

     Name  Age Department
2   Priya   23    Finance
3   Arjun   25         IT
4   Sneha   21  Marketing
5   Kiran   26         IT
6  Anjali   22         HR

In [17]:
df.tail(4)

     Name  Age Department
3   Arjun   25         IT
4   Sneha   21  Marketing
5   Kiran   26         IT
6  Anjali   22         HR

In [18]:
#info()=>method info provides a summary of the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        7 non-null      str
 1   Age         7 non-null      int64
 2   Department  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

In [ ]:
#describe()=>generates statistical information about numerical columns
df.describe()

             Age
count   7.000000
mean   23.285714
std     1.799471
min    21.000000
25%    22.000000
50%    23.000000
75%    24.500000
max    26.000000