In [1]:
import pandas as pd
data={
    "Name":["Swarna","Vighnesh","Keerthana","Sneha","Shruthi"],
    "Age":[21,22,20,24,23],
    "City":["Hyderabad","Mumbai","Hyderabad","Bangalore","Mumbai"],
    "Salary":[40000,50000,30000,45000,50000]
}
df=pd.DataFrame(data)
print(df)

        Name  Age       City  Salary
0     Swarna   21  Hyderabad   40000
1   Vighnesh   22     Mumbai   50000
2  Keerthana   20  Hyderabad   30000
3      Sneha   24  Bangalore   45000
4    Shruthi   23     Mumbai   50000

In [2]:
print(df["Name"])

0       Swarna
1     Vighnesh
2    Keerthana
3        Sneha
4      Shruthi
Name: Name, dtype: str

In [3]:
print(df[["Name","Salary"]])#when we selecting multiple columns,we use double square brackets

        Name  Salary
0     Swarna   40000
1   Vighnesh   50000
2  Keerthana   30000
3      Sneha   45000
4    Shruthi   50000

In [4]:
#loc[] vs iloc[]=>are used to select rows and columns
#loc[]=>selects using labels/names
#iloc=>selects using integer positions
#loc[]
print(df.loc[2])

Name      Keerthana
Age              20
City      Hyderabad
Salary        30000
Name: 2, dtype: object

In [5]:
print(df.loc[1:3,["Name","Salary"]])#in loc[] the ending index is also been included

        Name  Salary
1   Vighnesh   50000
2  Keerthana   30000
3      Sneha   45000

In [6]:
#iloc[]
print(df.iloc[2])

Name      Keerthana
Age              20
City      Hyderabad
Salary        30000
Name: 2, dtype: object

In [7]:
print(df.iloc[1:4,0:2])#it doesnot include ending index

        Name  Age
1   Vighnesh   22
2  Keerthana   20
3      Sneha   24

In [8]:
df.loc[1:3]

        Name  Age       City  Salary
1   Vighnesh   22     Mumbai   50000
2  Keerthana   20  Hyderabad   30000
3      Sneha   24  Bangalore   45000

In [9]:
df.iloc[1:3]

        Name  Age       City  Salary
1   Vighnesh   22     Mumbai   50000
2  Keerthana   20  Hyderabad   30000

In [10]:
#Boolean Filtering=>is used to select rows based on a condition
result=df[df["Salary"]>30000]
print(result)

       Name  Age       City  Salary
0    Swarna   21  Hyderabad   40000
1  Vighnesh   22     Mumbai   50000
3     Sneha   24  Bangalore   45000
4   Shruthi   23     Mumbai   50000

In [11]:
result=df[
    (df["Age"]>22) &
    (df["Salary"]>35000)
]
print(result)

      Name  Age       City  Salary
3    Sneha   24  Bangalore   45000
4  Shruthi   23     Mumbai   50000

In [12]:
result=df[
    (df["City"]=="Hyderabad") |
    (df["City"]=="Mumbai")
]
print(result)

        Name  Age       City  Salary
0     Swarna   21  Hyderabad   40000
1   Vighnesh   22     Mumbai   50000
2  Keerthana   20  Hyderabad   30000
4    Shruthi   23     Mumbai   50000

In [13]:
#isin()=>used to check whether values belong to a specified list of values
result=df[df["City"].isin(["Hyderabad","Mumbai"])]
print(result)

        Name  Age       City  Salary
0     Swarna   21  Hyderabad   40000
1   Vighnesh   22     Mumbai   50000
2  Keerthana   20  Hyderabad   30000
4    Shruthi   23     Mumbai   50000

In [14]:
#between()=>checks whether values fall within a specified range
#by default,both boundary values are included
result=df[df["Age"].between(22,24)]
print(result)

       Name  Age       City  Salary
1  Vighnesh   22     Mumbai   50000
3     Sneha   24  Bangalore   45000
4   Shruthi   23     Mumbai   50000

In [15]:
#Query()=>allows us to filter a dataframe using a string expression
#it cam make conditions more readable
result=df.query("Salary>30000")
print(result)

       Name  Age       City  Salary
0    Swarna   21  Hyderabad   40000
1  Vighnesh   22     Mumbai   50000
3     Sneha   24  Bangalore   45000
4   Shruthi   23     Mumbai   50000

In [16]:
result=df.query("Age>22 and Salary>35000")
print(result)

      Name  Age       City  Salary
3    Sneha   24  Bangalore   45000
4  Shruthi   23     Mumbai   50000

In [17]:
#sort_values()=>sort a dataframe based on the values in one or more columns
result=df.sort_values(by="Salary") #ascending order
print(result)

        Name  Age       City  Salary
2  Keerthana   20  Hyderabad   30000
0     Swarna   21  Hyderabad   40000
3      Sneha   24  Bangalore   45000
1   Vighnesh   22     Mumbai   50000
4    Shruthi   23     Mumbai   50000

In [18]:
#sorting in descending order
result=df.sort_values(
    by="Salary",
    ascending=False
)
print(result)

        Name  Age       City  Salary
1   Vighnesh   22     Mumbai   50000
4    Shruthi   23     Mumbai   50000
3      Sneha   24  Bangalore   45000
0     Swarna   21  Hyderabad   40000
2  Keerthana   20  Hyderabad   30000

In [19]:
#sort_index()=>used to sort datframe based on its index value
new_df=df.iloc[[3,1,4,0,2]]
print(new_df)

        Name  Age       City  Salary
3      Sneha   24  Bangalore   45000
1   Vighnesh   22     Mumbai   50000
4    Shruthi   23     Mumbai   50000
0     Swarna   21  Hyderabad   40000
2  Keerthana   20  Hyderabad   30000

In [20]:
#sort by index
result=new_df.sort_index()
print(result)

        Name  Age       City  Salary
0     Swarna   21  Hyderabad   40000
1   Vighnesh   22     Mumbai   50000
2  Keerthana   20  Hyderabad   30000
3      Sneha   24  Bangalore   45000
4    Shruthi   23     Mumbai   50000

In [21]:
#adding column and rows
df["Experience"]=[1,2,0,3,3]
print(df)

        Name  Age       City  Salary  Experience
0     Swarna   21  Hyderabad   40000           1
1   Vighnesh   22     Mumbai   50000           2
2  Keerthana   20  Hyderabad   30000           0
3      Sneha   24  Bangalore   45000           3
4    Shruthi   23     Mumbai   50000           3

In [22]:
#adding a calculated column
df["Bonus"]=df["Salary"]*0.10
print(df)

        Name  Age       City  Salary  Experience   Bonus
0     Swarna   21  Hyderabad   40000           1  4000.0
1   Vighnesh   22     Mumbai   50000           2  5000.0
2  Keerthana   20  Hyderabad   30000           0  3000.0
3      Sneha   24  Bangalore   45000           3  4500.0
4    Shruthi   23     Mumbai   50000           3  5000.0

In [23]:
#adding a new row
df.loc[len(df)]=["Hani",21,"Pune",45000,3,4500]#len(df)=>returns the next avilable row position
print(df)

        Name  Age       City  Salary  Experience   Bonus
0     Swarna   21  Hyderabad   40000           1  4000.0
1   Vighnesh   22     Mumbai   50000           2  5000.0
2  Keerthana   20  Hyderabad   30000           0  3000.0
3      Sneha   24  Bangalore   45000           3  4500.0
4    Shruthi   23     Mumbai   50000           3  5000.0
5       Hani   21       Pune   45000           3  4500.0

In [24]:
result=df.rename(
    columns={
        "Name":"Employee_Name",
        "Salary":"Monthly_Salary"
    }
)
print(result)

  Employee_Name  Age       City  Monthly_Salary  Experience   Bonus
0        Swarna   21  Hyderabad           40000           1  4000.0
1      Vighnesh   22     Mumbai           50000           2  5000.0
2     Keerthana   20  Hyderabad           30000           0  3000.0
3         Sneha   24  Bangalore           45000           3  4500.0
4       Shruthi   23     Mumbai           50000           3  5000.0
5          Hani   21       Pune           45000           3  4500.0

In [25]:
#renaming rows
result=df.rename(
    index={
        0:"A",
        1:"B",
        2:"C"
    }
)
print(result)

        Name  Age       City  Salary  Experience   Bonus
A     Swarna   21  Hyderabad   40000           1  4000.0
B   Vighnesh   22     Mumbai   50000           2  5000.0
C  Keerthana   20  Hyderabad   30000           0  3000.0
3      Sneha   24  Bangalore   45000           3  4500.0
4    Shruthi   23     Mumbai   50000           3  5000.0
5       Hani   21       Pune   45000           3  4500.0

In [26]:
#dropping columns and rows
#drop()=>is used to remove rows or columns from a dataframe
result=df.drop(columns="City")
print(result)

        Name  Age  Salary  Experience   Bonus
0     Swarna   21   40000           1  4000.0
1   Vighnesh   22   50000           2  5000.0
2  Keerthana   20   30000           0  3000.0
3      Sneha   24   45000           3  4500.0
4    Shruthi   23   50000           3  5000.0
5       Hani   21   45000           3  4500.0

In [27]:
#multiple columns
result = df.drop(columns=["City", "Age"])
print(result)

        Name  Salary  Experience   Bonus
0     Swarna   40000           1  4000.0
1   Vighnesh   50000           2  5000.0
2  Keerthana   30000           0  3000.0
3      Sneha   45000           3  4500.0
4    Shruthi   50000           3  5000.0
5       Hani   45000           3  4500.0

In [28]:
#dropping a row
result=df.drop(index=5)
print(result)

        Name  Age       City  Salary  Experience   Bonus
0     Swarna   21  Hyderabad   40000           1  4000.0
1   Vighnesh   22     Mumbai   50000           2  5000.0
2  Keerthana   20  Hyderabad   30000           0  3000.0
3      Sneha   24  Bangalore   45000           3  4500.0
4    Shruthi   23     Mumbai   50000           3  5000.0

In [29]:
#dropping multiple rows
result=df.drop(index=[3,4])
print(result)

        Name  Age       City  Salary  Experience   Bonus
0     Swarna   21  Hyderabad   40000           1  4000.0
1   Vighnesh   22     Mumbai   50000           2  5000.0
2  Keerthana   20  Hyderabad   30000           0  3000.0
5       Hani   21       Pune   45000           3  4500.0